# Generated by Django 3.2 on 2021-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_due_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('direction', models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], default='ltr', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='source_direction',
            field=models.CharField(blank=True, choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_language_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_direction',
            field=models.CharField(blank=True, choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_language_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
